#开发环境配置 服务器225
server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
    max-threads: 200
spring:
  redis:
    database: 0
    host: localhost
    port: 6379
    password:

# Log
logging:
  level:
    org.springframework:
      data: DEBUG
      security: DEBUG
    com.reemii.prison.mapper: DEBUG

